CREATE TABLE Organisation (
	ID INTEGER PRIMARY KEY,
	Name VARCHAR(35) NOT NULL
);

CREATE TABLE Volunteer (
	ID INTEGER PRIMARY KEY,
	FirstName VARCHAR(35),
	LastName VARCHAR(35),
	Username VARCHAR(35) NOT NULL,
	Password VARCHAR(50) NOT NULL
);

CREATE TABLE Skill (
	ID INTEGER PRIMARY KEY,
	Name VARCHAR(35) NOT NULL
);

CREATE TABLE VolunteerSkill (
	VolunteerID INTEGER NOT NULL,
	SkillID INTEGER NOT NULL,
	FOREIGN KEY (VolunteerID) REFERENCES Volunteer(ID) ON DELETE CASCADE,
	FOREIGN KEY (SkillID) REFERENCES Skill(ID) ON DELETE CASCADE,
	PRIMARY KEY (VolunteerID, SkillID)
);

CREATE TABLE Location (
	ID INTEGER PRIMARY KEY,
	Name VARCHAR(35) NOT NULL
);

CREATE TABLE Event (
	ID INTEGER PRIMARY KEY,
	Name VARCHAR(35) NOT NULL,
	StartDate DATETIME,
	EndDate DATETIME,
	LocationID INTEGER,
	OrganisationID INTEGER,
	FOREIGN KEY (LocationID) REFERENCES Location(ID),
	FOREIGN KEY (OrganisationID) REFERENCES Organisation(ID)
);

CREATE TABLE EventType (
	ID INTEGER PRIMARY KEY,
	Name VARCHAR(35) NOT NULL
);

CREATE TABLE EventTypeJunction (
	TypeID INTEGER NOT NULL,
	EventID INTEGER NOT NULL,
	FOREIGN KEY (TypeID) REFERENCES EventType(ID) ON DELETE CASCADE,
	FOREIGN KEY (EventID) REFERENCES Event(ID) ON DELETE CASCADE
);

CREATE TABLE VolunteerOpportunity (
	ID INTEGER PRIMARY KEY,
	VolunteerID INTEGER,
	EventID INTEGER NOT NULL,
	FOREIGN KEY (VolunteerID) REFERENCES Volunteer(ID) ON DELETE CASCADE,
	FOREIGN KEY (EventID) REFERENCES Event(ID) ON DELETE CASCADE
);

CREATE TABLE OpportunitySkill (
	OpportunityID INTEGER,
	SkillID INTEGER,
	FOREIGN KEY (OpportunityID) REFERENCES VolunteerOpportunity(ID) ON DELETE CASCADE,
	FOREIGN KEY (SkillID) REFERENCES Skill(ID) ON DELETE CASCADE
);